"""
D4 — Weekly Purchase Report Generator (Excel) for PackRight Industries
Generates a multi-sheet Excel report using openpyxl.
"""
import os
import math
from datetime import datetime, timedelta
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
import json

TODAY = datetime(2023, 12, 1)
CREDIT_LIMIT = 3000000

AVG_PRICES = {
    "M01":22850,"M02":22929,"M03":22660,"M04":23096,"M05":23887,
    "M06":23333,"M07":23379,"M08":23620,"M09":23057,"M10":22613,
    "M11":23756,"M12":23087,"M13":23547,"M14":23128
}

BOM_MAP = {
    "small_std":{"M01":0.18,"M05":0.12,"M06":0.008,"M08":0.015,"M11":0.002,"M13":0.05},
    "medium_std":{"M01":0.32,"M05":0.22,"M06":0.014,"M08":0.025,"M11":0.003,"M13":0.08},
    "medium_printed":{"M02":0.32,"M05":0.22,"M06":0.014,"M09":0.006,"M10":0.006,"M11":0.003,"M13":0.08},
    "small_printed":{"M02":0.18,"M05":0.12,"M06":0.008,"M09":0.003,"M10":0.003,"M11":0.002,"M13":0.05},
    "large_std":{"M01":0.55,"M05":0.38,"M06":0.022,"M08":0.04,"M11":0.005,"M14":0.12},
    "large_premium":{"M04":0.55,"M05":0.38,"M07":0.022,"M09":0.008,"M10":0.008,"M12":0.004,"M14":0.12},
}

# Styling constants
HEADER_FILL = PatternFill("solid", fgColor="1F4E79")
HEADER_FONT = Font(name="Calibri", bold=True, color="FFFFFF", size=11)
CRITICAL_FILL = PatternFill("solid", fgColor="FFCCCC")
WARNING_FILL = PatternFill("solid", fgColor="FFF2CC")
OK_FILL = PatternFill("solid", fgColor="CCE5CC")
TITLE_FONT = Font(name="Calibri", bold=True, size=16, color="1F4E79")
SUBTITLE_FONT = Font(name="Calibri", bold=True, size=12, color="2E75B6")
BOLD_FONT = Font(name="Calibri", bold=True, size=11)
NORMAL_FONT = Font(name="Calibri", size=11)
MONEY_FORMAT = '#,##0'
THIN_BORDER = Border(
    left=Side(style='thin'), right=Side(style='thin'),
    top=Side(style='thin'), bottom=Side(style='thin')
)

def style_header_row(ws, row, max_col):
    for col in range(1, max_col + 1):
        cell = ws.cell(row=row, column=col)
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.alignment = Alignment(horizontal="center", wrap_text=True)
        cell.border = THIN_BORDER

def auto_fit_columns(ws):
    for col in ws.columns:
        max_len = 0
        col_letter = get_column_letter(col[0].column)
        for cell in col:
            try:
                if cell.value:
                    max_len = max(max_len, len(str(cell.value)))
            except:
                pass
        ws.column_dimensions[col_letter].width = min(max_len + 3, 40)

def generate_report(forecast_df, alerts_df, substitution_df, procurement_df, 
                    upcoming_orders, explosion_df, output_dir):
    wb = Workbook()
    
    # ========== SHEET 1: Executive Summary ==========
    ws1 = wb.active
    ws1.title = "Executive Summary"
    ws1.sheet_properties.tabColor = "1F4E79"
    
    ws1.merge_cells("A1:H1")
    ws1["A1"] = "PackRight Industries — Weekly Procurement Report"
    ws1["A1"].font = TITLE_FONT
    ws1["A1"].alignment = Alignment(horizontal="center")
    
    ws1.merge_cells("A2:H2")
    ws1["A2"] = f"Report Date: {TODAY.strftime('%d %B %Y')} | Generated by AI Inventory System"
    ws1["A2"].font = Font(name="Calibri", italic=True, size=11, color="666666")
    ws1["A2"].alignment = Alignment(horizontal="center")
    
    critical_count = len(forecast_df[forecast_df["days_of_stock_remaining"] < 3])
    approved = procurement_df[procurement_df["status"].isin(["APPROVED","PARTIAL"])]
    total_orders_val = approved["order_cost_inr"].sum()
    final_outstanding = approved["cumulative_outstanding"].max() if len(approved) > 0 else 1414385
    credit_remaining = CREDIT_LIMIT - final_outstanding
    
    metrics = [
        ("Materials at CRITICAL Stock", str(critical_count), "FF0000"),
        ("Total Recommended Orders", f"Rs.{total_orders_val:,.0f}", "2E75B6"),
        ("Credit After Orders", f"Rs.{final_outstanding:,.0f} / Rs.{CREDIT_LIMIT:,}", "FF8C00"),
        ("Credit Remaining", f"Rs.{credit_remaining:,.0f}", "228B22"),
    ]
    
    row = 4
    for i, (label, value, color) in enumerate(metrics):
        col = (i * 2) + 1
        ws1.cell(row=row, column=col, value=label).font = BOLD_FONT
        c = ws1.cell(row=row+1, column=col, value=value)
        c.font = Font(name="Calibri", bold=True, size=14, color=color)
    
    row = 7
    ws1.cell(row=row, column=1, value="TOP 3 URGENT ACTIONS:").font = SUBTITLE_FONT
    urgent = forecast_df.sort_values("days_of_stock_remaining").head(3)
    for i, (_, u) in enumerate(urgent.iterrows()):
        ws1.cell(row=row+1+i, column=1, 
                 value=f"{i+1}. {u['material_id']} {u['material_name']}: {u['days_of_stock_remaining']} days remaining — ORDER NOW").font = BOLD_FONT
    
    auto_fit_columns(ws1)
    
    # ========== SHEET 2: Procurement Orders ==========
    ws2 = wb.create_sheet("Procurement Orders")
    ws2.sheet_properties.tabColor = "2E75B6"
    
    headers2 = ["Supplier","Material Code","Material Name","Current Stock","Unit",
                "Order Qty","MOQ","Unit Price Rs.","Total Value Rs.","Payment Terms",
                "Expected Delivery","Priority","Reason"]
    
    for c, h in enumerate(headers2, 1):
        ws2.cell(row=1, column=c, value=h)
    style_header_row(ws2, 1, len(headers2))
    ws2.freeze_panes = "A2"
    
    r = 2
    active_orders = procurement_df[procurement_df["order_qty_moq"] > 0].sort_values("supplier_id")
    sup_groups = active_orders.groupby("supplier_id") if len(active_orders) > 0 else []
    
    for sup_id, group in (sup_groups if len(active_orders) > 0 else []):
        for _, rec in group.iterrows():
            sup_info_lookup = {"lead_time_days": 7}
            lead = sup_info_lookup.get("lead_time_days", 7)
            exp_date = (TODAY + timedelta(days=lead)).strftime("%Y-%m-%d")
            
            vals = [rec["supplier_name"], rec["material_id"], rec["name"],
                   rec["current_stock"], rec["unit"], rec["order_qty_moq"],
                   "", rec["unit_price"], rec["order_cost_inr"],
                   rec["payment_terms"], exp_date, rec["priority"],
                   rec["recommendation_reason"]]
            
            for c, v in enumerate(vals, 1):
                cell = ws2.cell(row=r, column=c, value=v)
                cell.border = THIN_BORDER
                if rec["status"] == "BLOCKED":
                    cell.fill = CRITICAL_FILL
                elif "PARTIAL" in str(rec["status"]):
                    cell.fill = WARNING_FILL
                else:
                    cell.fill = OK_FILL
            r += 1
        
        ws2.cell(row=r, column=1, value=f"Subtotal — {sup_id}").font = BOLD_FONT
        ws2.cell(row=r, column=9, value=group["order_cost_inr"].sum()).font = BOLD_FONT
        r += 1
    
    ws2.cell(row=r, column=1, value="GRAND TOTAL").font = Font(bold=True, size=12)
    ws2.cell(row=r, column=9, value=active_orders["order_cost_inr"].sum() if len(active_orders) > 0 else 0).font = Font(bold=True, size=12)
    auto_fit_columns(ws2)
    
    # ========== SHEET 3: Stockout Risk Dashboard ==========
    ws3 = wb.create_sheet("Stockout Risk Dashboard")
    ws3.sheet_properties.tabColor = "FF0000"
    
    headers3 = ["Material","Current Stock","Daily Demand","Days Remaining",
                "21-Day Need","Shortfall","Alert Level","Action Required"]
    for c, h in enumerate(headers3, 1):
        ws3.cell(row=1, column=c, value=h)
    style_header_row(ws3, 1, len(headers3))
    ws3.freeze_panes = "A2"
    
    alerts_sorted = alerts_df.sort_values("days_remaining")
    for i, (_, a) in enumerate(alerts_sorted.iterrows(), 2):
        action = "ORDER IMMEDIATELY" if a["days_remaining"] < 3 else ("Monitor" if a["days_remaining"] <= 7 else "OK")
        vals = [f"{a['material_id']} {a['name']}", a["current_stock"],
               round(a["daily_demand"], 2), a["days_remaining"],
               a["21d_need"], a["shortfall"], a["alert_level"], action]
        for c, v in enumerate(vals, 1):
            cell = ws3.cell(row=i, column=c, value=v)
            cell.border = THIN_BORDER
            if a["days_remaining"] < 3:
                cell.fill = CRITICAL_FILL
            elif a["days_remaining"] <= 7:
                cell.fill = WARNING_FILL
            else:
                cell.fill = OK_FILL
    auto_fit_columns(ws3)
    
    # ========== SHEET 4: Substitution Advisory ==========
    ws4 = wb.create_sheet("Substitution Advisory")
    ws4.sheet_properties.tabColor = "FF8C00"
    
    if len(substitution_df) > 0:
        headers4 = list(substitution_df.columns)
        for c, h in enumerate(headers4, 1):
            ws4.cell(row=1, column=c, value=h)
        style_header_row(ws4, 1, len(headers4))
        for i, (_, row_data) in enumerate(substitution_df.iterrows(), 2):
            for c, h in enumerate(headers4, 1):
                cell = ws4.cell(row=i, column=c, value=row_data[h])
                cell.border = THIN_BORDER
    else:
        ws4.cell(row=1, column=1, value="No substitution advisories at this time.")
    auto_fit_columns(ws4)
    
    # ========== SHEET 5: Calculation Chain ==========
    ws5 = wb.create_sheet("Calculation Chain")
    ws5.sheet_properties.tabColor = "228B22"
    
    ws5.cell(row=1, column=1, value="FULL CALCULATION CHAIN — Every Material").font = TITLE_FONT
    ws5.merge_cells("A1:F1")
    
    r = 3
    for _, mat_row in forecast_df.sort_values("days_of_stock_remaining").iterrows():
        mat_id = mat_row["material_id"]
        mat_name = mat_row["material_name"]
        raw_demand = mat_row["raw_demand"]
        adj_demand = mat_row["adjusted_demand"]
        cs = mat_row["current_stock"]
        unit = mat_row["unit"]
        
        # Find matching orders
        mat_orders = explosion_df[explosion_df["material_id"] == mat_id] if explosion_df is not None else None
        order_count = len(mat_orders) if mat_orders is not None else 0
        
        # Find procurement rec
        proc = procurement_df[procurement_df["material_id"] == mat_id]
        
        ws5.cell(row=r, column=1, value=f"{mat_id}: {mat_name}").font = SUBTITLE_FONT
        r += 1
        
        lines = [
            f"Upcoming orders (next 42 days): {order_count} order line items",
            f"Raw demand from BOM explosion: {raw_demand:.2f} {unit}",
            f"Seasonal adjustment (Dec x1.40): {raw_demand:.2f} x 1.40 = {adj_demand:.2f} {unit}",
            f"Current stock: {cs} {unit}",
        ]
        
        order_needed = adj_demand - cs
        if order_needed > 0:
            lines.append(f"Order needed: {adj_demand:.2f} - {cs} = {order_needed:.2f} {unit}")
            if len(proc) > 0:
                p = proc.iloc[0]
                lines.append(f"Supplier: {p.get('supplier_id','?')} ({p.get('supplier_name','?')})")
                lines.append(f"MOQ rounding: {order_needed:.2f} -> {p.get('order_qty_moq',0)} {unit}")
                lines.append(f"Cost: {p.get('order_qty_moq',0)} x Rs.{AVG_PRICES.get(mat_id,0):,} = Rs.{p.get('order_cost_inr',0):,.0f}")
                lines.append(f"Payment terms: {p.get('payment_terms','?')} | Credit impact: Rs.{p.get('immediate_credit_impact',0):,.0f}")
                lines.append(f"Status: {p.get('status','?')}")
        else:
            lines.append(f"Stock sufficient: {cs} >= {adj_demand:.2f} -> NO ORDER NEEDED")
        
        for line in lines:
            ws5.cell(row=r, column=2, value=line).font = NORMAL_FONT
            r += 1
        r += 1
    
    auto_fit_columns(ws5)
    
    # Save
    os.makedirs(output_dir, exist_ok=True)
    filename = f"packright_weekly_report_{TODAY.strftime('%Y%m%d')}.xlsx"
    filepath = os.path.join(output_dir, filename)
    wb.save(filepath)
    
    print(f"\n  Excel report saved: {filepath}")
    return filepath

if __name__ == "__main__":
    print("Run via main.py")
